### ISSUE TITLE
Add a CLI option for exporting a vanilla ESLint config

### ISSUE THREAD

**Issue by jamestalmage** [xojs/xo#272]
See https://github.com/jamestalmage/xo-with-webstorm

Lots of editors support ESLint directly. Not that many support XO. We should add a `xo --export-config` command that outputs a `.eslintrc` file, and ensures all the correct packages are installed at the top level.

```
$ xo --export-config
This will overwrite the existing .eslintrc file. Ok? (y/n) y

Some of XO's modules need to be installed as top level dependencies for this to work.
Enter the following command:

   npm install --save-dev eslint-config-xo eslint-plugin... 
```

**Comment by sindresorhus** [comment]
Related to #122.

I'm ok with adding this flag.

**Comment by pvdlg** [comment]
XO has it own implementation of `overrides` which mean when we export the ESLint config we would have to translate from XO implementation to ESLint.

As it is now [supported by ESLint](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns), shouldn't we remove the XO `override` implementation and use ESLint one instead?

That would make this feature slightly easier to implement

**Comment by slikts** [comment]
Generating an ESLint config that would extend the XO config would make editor integrations work out-of-the-box for all the editors that support it; instead, now XO-specific [editor extensions][0] are required. I understand this is a legacy issue, but it's a significant letdown.

[0]: https://github.com/SamVerschueren/vscode-linter-xo

**Comment by fregante** [comment]
The new Flat config format essentially covers these needs:

- If you want an all-in-one dependency, install and run `xo`
- If you want an eslint config, install `eslint-config-xo`, which will _soon_ include all the necessary dependencies

Since this issue is now 5 years old with little progress/interest + Prettier and TypeScript having become dependencies (further complicating the endeavor), I'm closing in favor of 

- https://github.com/xojs/xo/issues/702
