### ISSUE TITLE
"prettier" in "extend" incompatible

### ISSUE THREAD

**Issue by pixelass** [xojs/xo#302]
## Issue description

When using `{"prettier": true}` inside a shareable config an error is thrown

Without the option no error occurs

## Config

**custom-config** 

```json
{
  "prettier": true,
  "parser": "babel-eslint",
  "rules": {
    "no-console": 2
  }
}
```

**package.json**

```json
{
  "xo": {
    "extends": [
      "./custom-config"
    ]
  }
}
```

## Error

```shell
Error: ESLint configuration in <PROJECT>/custom-config.json is invalid:
	- Unexpected top-level property "prettier".

```

## Versions

* xo 0.20.3
* node v8.9.4
* npm 5.6.0
* yarn 1.3.2

**Comment by pvdlg** [comment]
This is the intended behavior as `extends` is meant to reference a valid eslint shareable config.
The `prettier` option (as well as `space` or `semicolon`) is specific to XO.

In your shareable config you can use only valid eslint options.

As a side note your shareable config must be named `eslint-config-<name>` other it won't be imported. So your example doesn't work because your config is named `custom-config`.

**Comment by pixelass** [comment]
Ok, thank you for explaining. 
I got the part with the eslint-config. The `./` disables that though right?

I just switched to this now: 

```json
"xo": {
  "prettier": true,
  "extends": [
    "../../config/xo/config.json"
  ]
}
```

https://github.com/sinnerschrader/dekk/blob/master/%40dekk/deck/package.json#L66-L68

Closing as resolved.
