### ISSUE TITLE
unicorn/number-literal-case conflicts with Prettier

### ISSUE THREAD

**Issue by smiled0g** [xojs/xo#310]
Prettier uses lower-case for number literals, where the unicorn/number-literal-case rejects because it requires the uppercase.

Example: 
```
0x46281d8f8d0e9e94c424fd9d5ca67e6dd104d50c
```

**Comment by pvdlg** [comment]
When Prettier is enabled we use https://github.com/prettier/eslint-config-prettier to disable all the ESLint rules that are related to formatting and would conflict.
However the rules from `eslint-plugin-unicorn` are not included.

I think the best solution would be to add a `prettier` or a `no-style` config to `eslint-plugin-unicorn`. This config would be similar to `recommended` minus the rules that would conflict with Prettier.

This way in XO we would include `plugin:unicorn/recommended` is `prettier` is `false` or `plugin:unicorn/prettier` if `prettier` is `true`.
That would allow to maintain the list of rules we want to enable directly in `eslint-plugin-unicorn` rather than in Xo. So if we add a new rule to `eslint-plugin-unicorn` no need to modify XO.

@sindresorhus what's your though on this solution? Do you have a better idea?

**Comment by sindresorhus** [comment]
I don't think `eslint-plugin-unicorn` should care about Prettier. It's just a normal ESLint plugin and not tied to XO, even though we bundle it. We can either just override the recommended rules here or them manually.

**Comment by pvdlg** [comment]
Ok. That mean every time we add a rule to `eslint-plugin-unicorn` we would have to modify XO if it conflicts with Prettier. It shouldn't be a big deal though.

**Comment by sindresorhus** [comment]
@pvdlg Yes, but it's not a big deal.

**Comment by lydell** [comment]
> Ok. That mean every time we add a rule to eslint-plugin-unicorn we would have to modify XO if it conflicts with Prettier. It shouldn't be a big deal though.

Just as a heads up, eslint-config-prettier 3.1.0 added support for eslint-plugin-unicorn: https://github.com/prettier/eslint-config-prettier/blob/master/CHANGELOG.md#version-310-2018-09-22

**Comment by monramremawitdragonhead** [comment]
Hey you mother fuckers I have told u to leave me the fuck alone I don't
want to do any of this bullshit snymore
