### ISSUE TITLE
max-len rule not being set when used with prettier (shouldn't it default to prettier's printWidth option?)

### ISSUE THREAD

**Issue by niftylettuce** [xojs/xo#322]
I should think by default this rule would be set automatically/merged, so that `max-len` "code": is set to whatever prettier's `printWidth` option is (either the default or merged)

```
      "max-len": [
        "error",
        {
          "code": 80 <---- should be whatever prettier's printWidth is
        }
      ],
```

**Comment by pvdlg** [comment]
If you set `prettier` option to `true` then XO uses [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) which will returns an error if your code is not formatted according to Prettier format.

`max-len` is disabled in such case because it's Prettier via `eslint-plugin-prettier` that take care of checking that and reporting the error.
