### ISSUE TITLE
Unstable report file order

### ISSUE THREAD

**Issue by coreyfarrell** [xojs/xo#361]
I'm working on modernizing a larger project, currently fixing a couple hundred issues across a half dozen files.  An annoyance I'm having is that I make a bunch of fixes, run `xo` again, and the output is in a different order.  So often the last file shown is different from the previous run, so instead of working on one file at a time I have to keep jumping around.  It would be nice if the error report output were sorted by filename to avoid this.  I normally try to provide a PR but I'm not sure where to look for this.

**Comment by coreyfarrell** [comment]
I do not seem to be getting the same issue with `xo --reporter=stylish`.  It appears that `stylish` always produces output sorted by filename, but the default reporter sometimes does not.  It seems to be based on the content.  It seems to be based on the code.  For example:

test1.js:
```js
'use strict';
function Test1() {}
Test1();
this.Test1();
```

test2.js:
```
'use strict';
function Test2() {}
Test2();
```

In this case `xo` shows test2.js before test1.js, but `xo --reporter=stylish` shows test1.js before test2.js.  In this specific case it seems that `this.Test1();` in test1.js causes that file to be listed after test2.js.  Not sure why.

**Comment by sindresorhus** [comment]
Then it must be [`eslint-formatter-pretty`](https://github.com/sindresorhus/eslint-formatter-pretty) ruining the order somehow.

**Comment by jamestalmage** [comment]
The problem is [here](https://github.com/sindresorhus/eslint-formatter-pretty/blob/df5362c1259fd5d5a7a52cfb196321a54147efa5/index.js#L21).

I think the idea was to list the file with the "most problems" near the bottom. I think I originally proposed this behavior because I was working on a project that had multiple warnings (TODO's I think), in multiple files, and often my entire terminal would be filled with yellow but no red, and I'd have to scroll up to find an actual problem.

I'm in agreement that this should be improved. I have been annoyed by it myself, exactly as the OP describes.

We should definitely still list "warning only" files first. After that, we could sort a few ways.

  * The least amount of errors on the bottom - Then you can work bottom up, picking off the lowest hanging fruit first. This likely won't create the same frustration as the search order (if you remove an error from the file with the least of amount of errors, it should still have the least amount of errors).
  * Just sort by filename - This probably works fine, but I do like the first idea.

**Comment by coreyfarrell** [comment]
@jamestalmage That's a great idea, warnings only first, least number of errors last.

**Comment by jamestalmage** [comment]
@coreyfarrell - check out that PR ⬆️. See if it works better for you.
