### ISSUE TITLE
0.28.1 breaks support for space option in typescript

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/xo#445]
I assume #442 overrides the options set by space.

`npm i xo@0.28.0 && npx xo` works fine.
`npm i xo@0.28.1 && npx xo` does not.

**Comment by sindresorhus** [comment]
// @pvdlg

**Comment by pvdlg** [comment]
For Typescript files we set the rule `@typescript-eslint/indent` explicitly based on the XO `space` option: https://github.com/xojs/xo/blob/2e39794d5ad4017ed2545d9a43691d4c4b0f7ade/lib/options-manager.js#L285

So not surer what is the problem you are reporting.

Can you provide a reproductible case with your config, the file you lint and what report you get and expect?

**Comment by EdJoPaTo** [comment]
create a temp folder, put in a ts file, for example index.ts with this content:
```ts
export function foo(): void {
  console.log('bar');
}
```

and a package.json with this content
```json
{
  "name": "xo-testing",
  "xo": {
    "space": 2
  }
}
```

Then run these two commands:
```sh
npm i xo@0.28.0 && npx xo
npm i xo@0.28.1 && npx xo
```


Using 0.28.0 this works fine without errors. 
0.28.1 reports for the rule 'indent' (which is only javascript specific, not for typescript) for expected tabs.

**Comment by pvdlg** [comment]
Thanks! Will look into that tonight

**Comment by pvdlg** [comment]
So the problem is the `indent` rule is set in the default XO config: https://github.com/xojs/eslint-config-xo/blob/06e4e1416bdbf2df56984adca8039683ebad735c/index.js#L305

So as a result for TS files we end up with both `indent` and `@typescript-eslint/indent` to be set up.

Fixing https://github.com/xojs/eslint-config-xo-typescript/issues/23 will solve the issue

**Comment by pvdlg** [comment]
Never mind my last comment, the `indent` rule is not part of those.
