### ISSUE TITLE
Consider disabling node/file-extension-in-import in TypeScript projects

### ISSUE THREAD

**Issue by pizzafox** [xojs/xo#522]
The TypeScript compiler already errors on invalid imports so having a ([broken](https://github.com/mysticatea/eslint-plugin-node/issues/257)) plugin also reporting this as well isn't very useful.

**Comment by sindresorhus** [comment]
Yeah, we can disable it for TS only. PR welcome.

https://github.com/xojs/xo/blob/ecd05bcf9e434a4be782d79d116e9a7cbd1d9642/lib/options-manager.js#L318-L320

**Comment by fregante** [comment]
So _it seems_ that TS now (Since January) supports adding the .js extension and the types are picked up correctly in my short tests.

More context: https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937

In short, I think the rule should now be restored *but* somehow force the .js extension.

You can see it working here:  https://github.com/fregante/content-scripts-register-polyfill/pull/29/files#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R2

**Comment by jonahsnider** [comment]
The issue I had with the plugin is still open mysticatea/eslint-plugin-node#257, until it's fixed I don't think this rule should be enabled.
